version: '3'

services:
  base:
    build:
      context: ./debian_config/
    image: mike/debian_config
    container_name: base
  base_m:
    build: ./magento_config/
    image: mike/magento_config
    depends_on:
      - base
    container_name: base_m
  # m22:
  #   build: ./m22_config/
  #   depends_on:
  #     - base_m
  #   ports:
  #     - "82:80"
  #   volumes:
  #      - /Users/molochko/Sites/magento/magento-dev-dk/instances:/var/www/html/shared
  #   tty: true
  #   container_name: m22
  m23:
    build: ./m23_config/
    depends_on:
      - base_m
    ports:
      - "83:80"
      - "4306:3306"
    volumes:
       - /Path/To/Your/magento/magento2-dev-dk/instances:/var/www/html/shared
    tty: true
    container_name: m23