version: '3'
  
services:
  base:
    build: 
      context: ./debian_config/
      args:
        SSH_PRIVATE_KEY: ${RSA}
        SSH_PUBLIC_KEY: ${RSA_PUB}
    image: mike/debian_config
    container_name: base
  base_m:
    build: ./magento_config/
    image: mike/magento_config
    depends_on: 
      - base
    container_name: base_m
  m22:
    build: ./m22_config/
    depends_on: 
      - base_m
    ports: 
      - "82:80"
    tty: true
    container_name: m22
  m23:
    build: ./m23_config/
    depends_on: 
      - base_m
    ports: 
      - "83:80"
    tty: true
    container_name: m23