version: '3'

services:
  base:
    build:
      context: ./debian_config/
    image: mike/debian_config
    container_name: base
  base_m:
    build: ./magento_config/
    image: mike/magento_config
    depends_on:
      - base
    container_name: base_m
  m23:
    build: ./m23_config/
    image: mike/m23_config
    depends_on:
      - base_m
    ports:
      - "83:80"
      - "4306:3306"
    volumes:
      - src-volume-dk:/var/www/html/shared
    tty: true
    container_name: m23
volumes:
  src-volume-dk:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,soft,nfsvers=3
      device: ":/Path/To/Your/magento/magento2-dev-dk/instances"